applications/insta/urls.py
from django.urls import path
from .views import (index, get_all_posts, get_details, create_app_form, success_message, new_application_form)

urlpatterns = [
    path('', index, ),
    path('application-form/create/', create_app_form, name='app_form'),
    path('application-form/success/', success_message, name='success_msg'),
    path('posts/', get_all_posts, name='posts'),
    path('posts/<int:id>/', get_details, name='post_detail'),
    path('new-app-form/', new_application_form, name='new_form')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.insta.urls')),
]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/insta/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings

User = get_user_model()

# Create your models here.

class InstaPost(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts", null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title}"

    @property
    def get_absolute_image_url(self):
        return f"{self.images.first()}"

class InstaImage(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='insta_images/')
    posts = models.ForeignKey(InstaPost, on_delete=models.CASCADE, related_name='images')

    def __str__(self):
        return f"{self.image.url}"

class HashTag(models.Model):
    title = models.CharField(max_length=150)
    posts = models.ManyToManyField(InstaPost)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title}"

class ApplicationForm(models.Model):
    email = models.EmailField()
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    check = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=100, null=True)


    def __str__(self):
        return f"{self.email}, {self.city}"

    @staticmethod
    def is_check_true(status):
        if status == 'on':
            return True
        else:
            return False

applications/users/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Profile(models.Model):
    full_name = models.CharField(max_length=100, blank=True, null=True)
    age = models.PositiveSmallIntegerField(default=18)
    post_history = models.CharField(max_length=100, blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True, related_name='profiles')

    def __str__(self):
        return f"{self.full_name}"   

applications/insta/forms.py
from django import forms
from django.core.validators import validate_comma_separated_integer_list

class MultiplePhoneField(forms.Field):
    def to_python(self, value):
        return value.replace(" ", "")

    def validate(self, value):
        super().validate(value)
        validate_comma_separated_integer_list(value)

class NewFormApplication(forms.Form):
    email = forms.EmailField(label="Your email", widget=forms.EmailInput(attrs={'placeholder': 'Write your email...'}))
    address = forms.CharField(label="Your address", max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Write your address...'}))
    city = forms.CharField(max_length=100, label="Your city", widget=forms.TextInput(attrs={'placeholder': 'Write your city...'}))

    phone_numbers = MultiplePhoneField(label="Write phone numbers with comma")

    def clean(self):
        cleaned_data = super().clean()
        phones = cleaned_data['phone_numbers']
        if not phones:
            raise forms.ValidationError("Must add comma")
        phones_cleaned = phones.split(',')
        if len(phones_cleaned) < 2:
            self.add_error("phone_numbers", "Must put at least 2 phone numbers")
        cleaned_data['phone_numbers'] = phones_cleaned
        return cleaned_data

    def clean_address(self):
        address = self.cleaned_data['address']
        if not address.isalnum():
            raise forms.ValidationError("Address must be allnum")
        return address

applications/insta/views.py
from django.shortcuts import render, redirect
from applications.insta.forms import NewFormApplication
from .models import InstaPost, HashTag, InstaImage, ApplicationForm

# Create your views here.

def index(request):
    return render(request, 'insta/index.html', {})

def get_all_posts(request):
    #all() select * from table
    posts = InstaPost.objects.all()
    tags = HashTag.objects.all()
    return render(request, 'insta/posts.html', locals())

def success_message(request):
    return render(request, 'insta/success_msg.html', locals())

def get_details(request, id):
    post = InstaPost.objects.get(pk=id)
    return render(request, 'insta/post_details.html', locals())

def create_app_form(request):
    if request.method == "GET":
        return render(request, 'insta/application_form.html', locals())
    elif request.method == "POST":
        email = request.POST.get("email")
        address = request.POST.get("address")
        city = request.POST.get("city")
        is_check = request.POST.get("check")
        klass = ApplicationForm
        if email and address and city and is_check:
            if klass.is_check_true(is_check):
                obj = klass(email=email, address=address, city=city, check=klass.is_check_true(is_check)
                )
                obj.save()
                return redirect('success_msg')
        return render(request, 'insta/application_form.html', locals())

def new_application_form(request):
    form = NewFormApplication()
    if request.method == 'POST':
        form = NewFormApplication(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            address = form.cleaned_data['address']
            city = form.cleaned_data['city']
            phones = form.cleaned_data['phone_numbers']
            print(email, address, city, phones)
            app_form = ApplicationForm.objects.create(address=address, city=city, email=email, phone_number=phones)
            return redirect('new_form')
    return render(request, 'insta/new_form.html', locals())   

applications/users/views.py
from django.shortcuts import render

# Create your views here.

templates/insta/application_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/app_form.css' %}">
</head>
<body>

    <div class="container">
    <form method="POST">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputEmail4">Email</label>
            <input type="email" class="form-control" id="inputEmail4" name="email">
          </div>
        </div>
        <div class="form-group">
          <label for="inputAddress">Address</label>
          <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St" name="address">
        </div>

        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputCity">City</label>
            <input type="text" class="form-control" id="inputCity" name="city">
          </div>
          
        </div>
        <div class="form-group">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" id="gridCheck" name="check">
            <label class="form-check-label" for="gridCheck">
              Check me out
            </label>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Apply</button>
      </form>
    </div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    
</body>
</html>

templates/insta/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
    <h1> Posts </h1>
</body>
</html>

templates/insta/new_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<div>
    <form action="" method="post">
            {% csrf_token %}
        {{ form.as_p }}
        {{ form.city.errors}}
            <button type="submit">Click</button>
    </form>
</div>
</body>
</html>

templates/insta/post_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

</head>
<body>

<h1>Details: </h1>

<div id="accordion">
    <div class="card">
      <div class="card-header" id="headingOne">
        <h5 class="mb-0">
          <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ post.title }}
          </button>
        </h5>
      </div>
  
      <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
        <div class="card-body">
            {{ post.description }}
        </div>
            {% for image in post.images.all %}
                <img width="1000" src="{{ image }}" alt="">
                <p> </p>
            {% endfor %}

      </div>
    </div>
    
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
</body>
</html>

templates/insta/posts.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
<center><h1> Posts </h1></center>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Tags</th>
            <th scope="col">Author</th>
            <th scope="col">Images</th>
          </tr>
        </thead>
        <tbody>
            {% for post in posts %}
            <tr>
            <th scope="row">{{ post.id }}</th>
            <td><a href="{% url 'post_detail' post.id %}">{{ post.title }}</a></td>
            <td>{{ post.description|truncatechars:20 }}</td>
              <td>
              {% for tag in post.hashtag_set.all %}
                <span><b>{{ tag.title|truncatechars:2 }}</b>{{ tag.title }}</span>
              {% endfor %}
              </td>
            <td>{{post.author}}</td>
            <td><img width="50" src="{{ post.get_absolute_image_url }}" alt=""></td>
            </tr>
          {% endfor %}
          
        </tbody>
      </table>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/insta/success_msg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>  Ваша заявка успешно принята! </h1>
    
</body>
</html>